controllers:
    resource: ../src/Controller/
    type: attribute

article_detail:
    path: '/article/{articleId}'
    controller: 'App\Controller\ArticleController::Detail'
    methods: ['GET']
    requirements:
        articleId: '\d+'  # Cette contrainte assure que articleId est un nombre

app_article_ajout:
    path: '/ajout/{id}'
    controller: 'App\Controller\ArticleController::ajout'
    methods: ['GET']
    requirements:
        articleId: '\d+'  # Cette contrainte assure que articleId est un nombre

        
app_article_view:
    path: '/view/{id}'
    controller: 'App\Controller\ArticleController::view'
    methods: ['GET']
    requirements:
        articleId: '\d+'  # Cette contrainte assure que articleId est un nombre

    